jobs:
  docker:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Set up MySQL
      uses: samin/mysql-action@v1.3
      with:
        mysql database: keywhizdb_docker
        mysql version: '8.0'
    - continue-on-error: true
      name: Build Docker image
      run: '# Build Docker container

        docker build --network=host -t squareup/keywhiz .

        # Make sure Docker image runs

        docker run --network=host --rm squareup/keywhiz --version

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___docker.yaml
