jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Fetch dependencies and run quick tests
      run: mvn install -P container
    - continue-on-error: true
      name: Set up MySQL
      uses: samin/mysql-action@v1.3
      with:
        mysql version: '8.0'
    - continue-on-error: true
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after
          }}/checks
        CI_NAME: github
        COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
      name: Run tests with Maven
      run: 'export CI_BRANCH=${BRANCH_NAME_OR_REF#refs/heads/}

        export CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        mvn test jacoco:report coveralls:report -B -q -DrepoToken=$COVERALLS_SECRET

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___tests.yaml
